# Generated by Django 6.1.1 on 2026-09-10 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="Ism")),
                (
                    "last_name",
                    models.CharField(max_length=100, verbose_name="Familiya"),
                ),
                (
                    "phone_number",
                    models.CharField(max_length=30, verbose_name="Telefon raqam"),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Email manzil"),
                ),
                ("message", models.TextField(verbose_name="Yuborilgan xabar")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yuborilgan vaqti"
                    ),
                ),
            ],
            options={
                "verbose_name": "Xabar",
                "verbose_name_plural": "Xabarlar",
                "ordering": ["id"],
            },
        ),
    ]
